import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" href="./globals.css" as="style" media="print" onLoad={"this.media='all';this.onload=null"}></link>
      </head>
      <body>{children}</body>
    </html>
  )
}
